### PR TITLE
CIBA was standardised last September

### PR DESCRIPTION
**Pull request by PieterKas**
Added clarification that CIBA is not a standard under development, but was completed in September 2021 and added references to the completed standard.

### CODE REVIEW

**Comment by PieterKas** [comment]
Refer back to issue #11

**Review by bc-pi — CHANGES_REQUESTED** [review]
CIBA core is not part of FAPI. Due to historical reasons CIBA core is actually a product of the MODRNA WG. In this context it's probably better to leave the WG out of it and just say it's an OIDF thing.

**Comment by PieterKas** [comment]
Thanks for that bit of historic context Brian. I will remove those references.

**Review by jogu — APPROVED** [review]

**Comment by PieterKas** [comment]
Thanks @jogu and @bc-pi - I also added you to the acknowledgment section.

**Pull request merged**
